### ISSUE TITLE
[Soundcloud] multiple pages errors

### ISSUE THREAD

**Issue by farfromrefug** [mmth/simplify_web_suite_core#12]
So here is what i have:
- very last simplify with the soundcloud bug fix with NSNull
- chrome extension where i changed ```large``` to ```t500x500````

Now i just realised some annoying bugs, the extension doesn't handle multiple soundcloud pages correctly.
I have 3 pages opened.
When i do play in the simplify player it goes mad and i see it switching between infos of the 3 pages and always seems to be loading the last one.
Sometimes infos are not corresponding to the actual playing page (soundcloud handles multiple pages on its own and pause all other pages when start playing one).
For example right now i see infos from page 3 while playing page 2.
If i play page 3 then i see infos from page2 ... 

/cc @mutewinter

**Comment by balupton** [comment]
Not sure if this is the right issue, but simplify for me doesn't seem to be picking up soundcloud with the safari extension installed.

**Comment by din** [comment]
@balupton, hello! Can you please compose an email to support@mmth.us about your issue and your environment (version) details, so we can help you? Thank you!
